backend:
  name: github
  repo: se7ka-gh/svn-lab-site-qwen
  branch: main

media_folder: "images/projects"
public_folder: "/images/projects"

locale: "ru"

collections:
  - name: "projects"
    label: "Проекты"
    folder: "projects"
    create: true
    fields:
      - {label: "Название", name: "name", widget: "string"}
      - {label: "Статус", name: "status", widget: "select", options: ["ready", "forsale", "inprogress"]}
      - {label: "Цена", name: "price", widget: "number", required: false}
      - {label: "Описание", name: "description", widget: "text"}
      - {label: "Обложка", name: "cover_image", widget: "image"}
